name = "ariang"
type = "webpack"
account_id = "1e752e20ad8ac6b74a275b64f272ef76"
route = 'ariang.linjinbao.tk/*'
zone_id = '02b23e0f77225f085046a173e2402a25'
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./public",entry-point = "workers-site"}
